### ISSUE TITLE
Localisation

### ISSUE THREAD

**Issue by ajnyga** [ajnyga/mostRead#10]
https://forum.pkp.sfu.ca/t/most-read-article-plugin-for-ojs-3-1-1-2/49166/35

**Comment by ctgraham** [comment]
I would suggest storing the metric count and article id in the cache.  Then, in `getContents()` fetch the article into the array to be passed into the template.  That way, you have the article object available in the template, for whatever methods you need (including `getLocalizedTitle()`).

**Comment by ajnyga** [comment]
Moving to this solution, thanks Clinton.
