### ISSUE TITLE
Replace serialize/unserialize with json_encode/json_decode or similar

### ISSUE THREAD

**Issue by ctgraham** [ajnyga/mostRead#11]
See: https://github.com/pkp/pkp-lib/issues/5302

https://github.com/ajnyga/mostRead/blob/2e256f4853e49cb6f4c450353dc0af82ad67c7f0/MostReadSettingsForm.inc.php#L42
https://github.com/ajnyga/mostRead/blob/2e256f4853e49cb6f4c450353dc0af82ad67c7f0/MostReadSettingsForm.inc.php#L68
https://github.com/ajnyga/mostRead/blob/2e256f4853e49cb6f4c450353dc0af82ad67c7f0/MostReadBlockPlugin.inc.php#L111

On the other hand, shouldn't `getSetting()` / `updateSetting()` handle the storing and fetching of a localized setting as an array?

**Comment by ajnyga** [comment]
moved to json_decode/encode. My understanding is that arrays wont work?
