### ISSUE TITLE
plugin fails if a most read article has been deleted

### ISSUE THREAD

**Issue by jnugent** [ajnyga/mostRead#17]
Found in most recent branches.  

The cacheMiss function fetches most read metrics and then builds article objects by calling 

`$submissionDao->getById($submissionId);`

But this will return null if the submission has since been deleted.  The Submission DAO classes do not clean up the metrics table. Suggest adding a test for the `$article` object before calling other methods, just in case, after this line:

https://github.com/ajnyga/mostRead/blob/master/MostReadBlockPlugin.inc.php#L160

This fatal error will break the journal sidebar.  This is probably a strange edge case since it is probably not often that a "most read" article has been deleted but it just happened to one of our hosted clients.

**Comment by ajnyga** [comment]
This is added to the new 3.4 version
