### ISSUE TITLE
Wrong localization for article title in multilingual journals

### ISSUE THREAD

**Issue by israelcefrin** [ajnyga/mostRead#18]
When a journal is multilingual using languages, the titles are shown in one language only and don't change correctly when the user switches the journal reading language.

https://user-images.githubusercontent.com/4992902/107375128-666ddc00-6ab6-11eb-9077-7c4e2347ffac.mov

**Comment by ajnyga** [comment]
Thanks, it's the same issue as this. https://github.com/ajnyga/mostRead/issues/10

**Comment by israelcefrin** [comment]
Perfect, I haven't seen that one (neither looked for similar, sorry). Please, feel free to close this one and keep everything there if you like. I can even include the video there, just for the records.

**Comment by ajnyga** [comment]
The new version for 3.4 that is the current master branch should fix this.
