### ISSUE TITLE
Locale pt_BR format po

### ISSUE THREAD

**Issue by antsoftsystems** [ajnyga/mostRead#20]
@ajnyga, initially good job with this plugin. Below is a suggested translation into Portuguese Brazil. 

msgid ""
msgstr ""
"Project-Id-Version: \n"
"Report-Msgid-Bugs-To: \n"
"Last-Translator: \n"
"Language-Team: \n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"POT-Creation-Date: 2021-06-09T10:36:44+02:00\n"
"PO-Revision-Date: 2021-06-09T10:36:44+02:00\n"
"Language: \n"

msgid "plugins.blocks.mostRead.displayName"
msgstr "Bloco de artigos mais lidos"

msgid "plugins.blocks.mostRead.description"
msgstr "Este plugin mostra artigos mais lidos na barra lateral."

msgid "plugins.blocks.mostRead.blockTitle"
msgstr "Mais lidos na semana passada"

msgid "plugins.blocks.mostRead.settings.title"
msgstr "Configurações Most Read Block"

msgid "plugins.blocks.mostRead.settings.days"
msgstr "Contagem de dias"

msgid "plugins.blocks.mostRead.settings.blockTitle"
msgstr "Título do bloco"

msgid "plugins.blocks.mostRead.settings.saved"
msgstr "configurações do plug-in do bloco de artigos mais lido salvas"

**Comment by ajnyga** [comment]
thanks for this, I will add it to the 3.4 release

**Comment by antsoftsystems** [comment]
Fixes

msgid "plugins.blocks.mostRead.blockTitle"
msgstr "Artigos mais lidos"

msgid "plugins.blocks.mostRead.settings.saved"
msgstr "Configurações do plug-in do bloco de artigos mais lido"
