### ISSUE TITLE
Error Occured when opening plugin setting

### ISSUE THREAD

**Issue by asrarahmadehsan** [ajnyga/mostRead#21]
I am using OJS version 3.3.0-11 and installing MostRead plugin but when I open the setting of the plugin the following error occurs:
`Failed Ajax request or invalid JSON format`.

**Comment by Maxwell-23** [comment]
Hello, has your problem been resolved? I have the same problem!

**Comment by rkhalikov** [comment]
The same problem. OJS 3.3.0-17, PHP 8.1.27. @ajnyga, we definitely need help...

`[lsapi:error] Backend fatal error: PHP Fatal error:  Uncaught Error: Non-static method PKPApplication::getRequest() cannot be called statically in .../plugins/blocks/mostRead/MostReadBlockPlugin.inc.php:70\nStack trace:\n#0 .../lib/pkp/classes/controllers/grid/plugins/PluginGridHandler.inc.php(236): MostReadBlockPlugin->manage()\n#1 .../lib/pkp/classes/core/PKPRouter.inc.php(397): PluginGridHandler->manage()\n#2 .../lib/pkp/classes/core/PKPComponentRouter.inc.php(257): PKPRouter->_authorizeInitializeAndCallRequest()\n#3 .../lib/pkp/classes/core/Dispatcher.inc.php(144): PKPComponentRouter->route()\n#4 .../lib/pkp/classes/core/PKPApplication.inc.php(360): Dispatcher->dispatch()\n#5 .../index.php(68): PKPApplication->execute()\n#6 {main}\n  thrown in .../plugins/blocks/mostRead/MostReadBlockPlugin.inc.php on line 70\n`

**Comment by ajnyga** [comment]
I made a release for OJS 3.3. https://github.com/ajnyga/mostRead/releases

Sorry for the delay, this is a plugin I have not been actively supporting.

**Comment by rkhalikov** [comment]
Excellent! Thank you, @ajnyga! I updated the plugin, everything works now.

Two questions remain for the future. What about your plans for 3.5 LTS? We'll definitely skip 3.4... Maybe your plugin will finally make it into the PKP gallery? Multilingualism is the second question that we discussed several years ago %), https://forum.pkp.sfu.ca/t/most-read-article-plugin-for-ojs-3-1-1-2/49166/31
