### ISSUE TITLE
Add Support for OJS 3.4.0-5

### ISSUE THREAD

**Issue by syedmughees** [ajnyga/mostRead#24]
This plugin is only compatible till OJS 3.3.0-15 please Add Support for OJS 3.4.0-5

**Comment by ajnyga** [comment]
I do plan to do this, but the statistics database is completely different in 3.4 so I need to look into the new code and db structure first.

**Comment by zielaq** [comment]
I will have update to 3.4 in few next days

**Comment by ajnyga** [comment]
Current master branch should now be 3.4 compliant. Still going to do small changes.

The new version now supports multilinguality better.

It uses the new statistics endpoint in OJS, note that I have no idea how fast that endpoint is in larger installations, so feedback in that regard is wellcome.
