### ISSUE TITLE
Explain Days Count 

### ISSUE THREAD

**Issue by nhsoman** [ajnyga/mostRead#25]
I would like to know what is the days count value for?

and how to display in a side bar

**Comment by ajnyga** [comment]
The days count value is to determine what is the time limit for showing the statistics. By default it is 7, but if you want to show statistics from the past 30 days instead, you can enter that value.

You can display the block by enabling the plugin in the plugin settings page and the by activating it in the sidebar in the website settings section in OJS settings.
