### ISSUE TITLE
Include subtitle in article list

### ISSUE THREAD

**Issue by jnugent** [ajnyga/mostRead#3]
Hi Anti-Jussi,

We have a hosted journal that is currently using the plugin.  They have a lot of articles that have an article title ending with a colon, because they also have a subtitle. The plugin only displays the article title, which means that their most read article list has a number of titles ending in a colon.  Could the plugin also include the subtitle?

Thanks!
Jason

**Comment by ajnyga** [comment]
Sure, Bozana did a code review for this a while ago and have to look at that as well.

**Comment by jnugent** [comment]
#4 closes this issue.
