### ISSUE TITLE
Not actually an issue just question. 

### ISSUE THREAD

**Issue by navotera** [ajnyga/mostRead#6]
I want to customize this plugin but by MostViewed. 

MostViewed is taken from which galley is most downloaded. Any ideas which table from OJS should I consider?

Thank

**Comment by ajnyga** [comment]
Sorry for the delay. The table for all statistics in OJS is called "metrics". There are different types of metrics there so you need to know which type you are looking for. You should check the OJS code in github for examples.

**Comment by navotera** [comment]
Thank you so much @ajnyga for the hint
